version: "3"

vars:
  BINARY_NAME: "kubesnake"
  IMAGE_TAG: "kubesnake:dev"
  K3D_CLUSTER_NAME: "kubesnake-dev"
  KUBECONFIG_CONTEXT: "k3d-{{.K3D_CLUSTER_NAME}}"

tasks:
  ##########################################################
  # Build Tasks
  ##########################################################

  build:
    desc: Build kubesnake for all platforms (linux/amd64, linux/arm64)
    cmds:
      - ./scripts/build.sh all

  build:docker:
    desc: Build the Docker image
    cmds:
      - docker build -t {{.IMAGE_TAG}} -f build/package/Dockerfile .

  test:
    desc: Run all tests
    cmds:
      - task: test:unit
      - task: test:e2e

  test:unit:
    desc: Run tests
    deps: [prepare:certs]
    cmds:
      - go test -v ./...

  test:e2e:
    desc: Run all e2e test scenarios (parallel)
    vars:
      PARALLEL_SUITES: 4
    deps: [build]
    cmds:
      - time go test -count=1 -tags e2e -v -p {{.PARALLEL_SUITES}} ./test/...

  test:e2e:serial:
    desc: Run all e2e test scenarios (serial)
    cmds:
      - time go test -count=1 -tags e2e -v -p 1 ./test/...

  lint:
    desc: Run linters
    deps: [prepare:certs]
    cmds:
      - go vet ./...

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  prepare:certs:
    desc: Copy system CA bundle for embedding
    cmds:
      - ./scripts/copy-certs.sh

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf dist/

  ##########################################################
  # Cluster Tasks
  ##########################################################

  up:
    desc: Basic cluster is running and ready
    vars:
      START_TIME:
        sh: date +%s
    cmds:
      - task: k3d:create
      - task: k3d:kubeconfig
      - kubectl get nodes
      - echo "Cluster ready in $(($(date +%s) - {{.START_TIME}}))s"

  down:
    desc: Delete the cluster
    cmds:
      - task k3d:delete

  k3d:install:
    desc: Install k3d
    cmds:
      - ./scripts/k3d-install.sh

  k3d:create:
    desc: Create a k3s test cluster for KubeSnake
    cmds:
      - k3d cluster create {{.K3D_CLUSTER_NAME}}
        --servers 1
        --agents 2
        --api-port 6443
        --k3s-arg '--disable=traefik@server:*'
        --k3s-arg '--disable=servicelb@server:*'

  k3d:delete:
    desc: Delete the dev cluster
    cmds:
      - k3d cluster delete {{.K3D_CLUSTER_NAME}}

  k3d:kubeconfig:
    desc: Export kubeconfig for this cluster
    cmds:
      - k3d kubeconfig merge {{.K3D_CLUSTER_NAME}} --kubeconfig-switch-context

  k3d:useconfig:
    desc: Use the kubeconfig for this cluster
    cmds:
      - kubectl config use-context {{.KUBECONFIG_CONTEXT}}

  k3d:loadimage:
    desc: Load local kubesnake:dev image into the dev cluster
    cmds:
      - k3d image import {{.IMAGE_TAG}} -c {{.K3D_CLUSTER_NAME}}

  k3d:upload:
    desc: Upload the kubesnake binary to the dev cluster
    cmds:
      - kubectl apply -f test/manual/manifests/basic-execution.yaml
      - sleep 5
      - kubectl cp dist/kubesnake-linux-amd64 default/basic-pod:/tmp/kubesnake-amd64
      - kubectl cp dist/kubesnake-linux-arm64 default/basic-pod:/tmp/kubesnake-arm64
      - kubectl exec -it -n default basic-pod -- /bin/bash
